name: AD-B2C custom policies release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      StorageAccountPath: https://jitvcstorage.blob.core.windows.net/devopsbranding/branding/


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update TrustFrameworkBase.xml
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-deployment-script.ps1 -ClientID $ -ClientSecret $ -TenantId $ -PolicyId B2C_1A_TrustFrameworkBase -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\custom-policies\TrustFrameworkBase.xml -ProxyIdentityExperienceFrameworkAppId $ -IdentityExperienceFrameworkAppId $ -StorageAccountPath $env:StorageAccountPath
          
      - name: Update TrustFrameworkExtensions.xml
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-deployment-script.ps1 -ClientID $ -ClientSecret $ -TenantId $ -PolicyId B2C_1A_TrustFrameworkExtensions -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\custom-policies\TrustFrameworkExtensions.xml -ProxyIdentityExperienceFrameworkAppId $ -IdentityExperienceFrameworkAppId $ -FacebookClientId $

      - name: Update SignUpOrSignin.xml
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-deployment-script.ps1 -ClientID $ -ClientSecret $ -TenantId $ -PolicyId B2C_1A_SignUpOrSignin -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\custom-policies\SignUpOrSignin.xml -ProxyIdentityExperienceFrameworkAppId $ -IdentityExperienceFrameworkAppId $
          
      - name: Update PasswordReset.xml
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-deployment-script.ps1 -ClientID $ -ClientSecret $ -TenantId $ -PolicyId B2C_1A_PasswordReset -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\custom-policies\PasswordReset.xml -ProxyIdentityExperienceFrameworkAppId $ -IdentityExperienceFrameworkAppId $

      - name: Update ProfileEdit.xml
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-deployment-script.ps1 -ClientID $ -ClientSecret $ -TenantId $ -PolicyId B2C_1A_ProfileEdit -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\custom-policies\ProfileEdit.xml -ProxyIdentityExperienceFrameworkAppId $ -IdentityExperienceFrameworkAppId $

      - name: Replace Storage Account Path in exception html file
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-branding-deployment-script.ps1 -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\branding\template\exception.html -StorageAccountPath $env:StorageAccountPath
  
      - name: Replace Storage Account Path in idpSelector html file
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-branding-deployment-script.ps1 -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\branding\template\idpSelector.html -StorageAccountPath $env:StorageAccountPath

      - name: Replace Storage Account Path in multifactor-1.0.0 html file
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-branding-deployment-script.ps1 -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\branding\template\multifactor-1.0.0.html -StorageAccountPath $env:StorageAccountPath
          
      - name: Replace Storage Account Path in phoneFactor html file
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-branding-deployment-script.ps1 -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\branding\template\phoneFactor.html -StorageAccountPath $env:StorageAccountPath
          
      - name: Replace Storage Account Path in selfAsserted html file
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-branding-deployment-script.ps1 -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\branding\template\selfAsserted.html -StorageAccountPath $env:StorageAccountPath

      - name: Replace Storage Account Path in unified html file
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-branding-deployment-script.ps1 -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\branding\template\unified.html -StorageAccountPath $env:StorageAccountPath
          
      - name: Replace Storage Account Path in updateProfile html file
        shell: pwsh
        run: |
          .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\scripts\custom-policies-branding-deployment-script.ps1 -PathToFile .\src\ad-b2c-templates\ad-b2c-custom-policies-generic\branding\template\updateProfile.html -StorageAccountPath $env:StorageAccountPath

      - name: Upload AD B2C branding files
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7
        with:
          connection_string: $
          container_name: ad-b2c-branding
          source_folder: src/ad-b2c-templates/ad-b2c-custom-policies-generic/branding/
          destination_folder: branding
          clean_destination_folder: true
